### ISSUE TITLE
Feature Request: Restart task rather than create new instance every time

### ISSUE THREAD

**Issue by Mustack** [pghalliday/alarmist#1]
Hi,

I'm loving Alarmist so far. It's a very neat tool to organize my scripts.

One problem I'm running into is that some of my scripts are being run many times in parallel. This is because those scripts take a long time to execute (~30 seconds) and saving files frequently causes my build script to run many instances. When it gets bad, my machine starts lagging because I've got too many resource-heavy processes running in parallel.

I think it would be really handy if alarmist could handle killing ongoing processes before starting new ones. When a task is started with alarmist-npm, before executing that task, it could check to see if it's already running that same task. If it's already running, it could kill it and then start it again.

What do you think? I might take a shot at implementing this but I wanted to start a discussion about it first.

**Comment by pghalliday** [comment]
Wow, sorry I missed this - I have been quite distracted the last few months. It sounds like it could be a good option. Particularly when running the same job in parallel can possibly cause a conflict. I'm going to refresh my memory as to how this might be done

**Comment by pghalliday** [comment]
I think it would be necessary to record the PID of a running job in the job directory, and clean it up when a job completes. That way a new job could see the PID file and kill that process before starting. Passing in the option through the CLI may be trickier and expose a deficiency in the architecture though, I can foresee a problem of having to propagate the option to the helper libraries like `alarmist-npm` too.

Another possible approach might be to create a "simple" wrapper executable script or something that enforces this behaviour. This would be outside the scope of `alarmist` but could be a more unix way of doing things. I might call such a utility `kill-and-restart` and it would pipe the stdout and stderr through while recording a running PID so that it can kill anything running (maybe it could also force a special exit code by handling whatever signal is used to kill it).

**Comment by pghalliday** [comment]
Ok so i've been working on some new features and have been giving this request some more thought. The way I see it is that it would be a poor workaround to implement this within alarmist. However, I do think there is a sensible way forward.

You will notice that in my examples I use `chokidar-cli` to watch for changes and kick off jobs. As a result the individual job runs don't really know about each other and the monitor doesn't know about the processes either (it doesn't even know if they are separate processes).

It might be possible to plumb something together by recording PIDs, etc but I can see that it could be quite fragile or even dangerous (note that PIDs are eventually reused by the OS and we cannot be sure everything has been cleaned up correctly).

On the other hand `chokidar-cli` is actually spawning these child processes and as such should have a direct reference to them. I would suggest that this is where the option to restart processes should be implemented. And as such you could try raising a feature request over there.

https://github.com/kimmobrunfeldt/chokidar-cli

It should be noted that you're not the only one that has run into this problem with `chokidar-cli` and in fact they already implemented 2 features that might alleviate the problem:

```
  -d, --debounce          Debounce timeout in ms for executing command
                                                                  [default: 400]
  -t, --throttle          Throttle timeout in ms for executing command
                                                                  [default: 0]
```

I think these flags were added in response to the following issue (which is pretty much the problem you are describing)

https://github.com/kimmobrunfeldt/chokidar-cli/issues/13

However I think that a `-r, --restart` option would also be quite useful. It would have to be implemented in such a way that the whole child process tree is stopped though (in the past I have found it to be all too easy to orphan processes when killing them in node)

**Comment by Mustack** [comment]
Wow! Thanks for your thorough thoughts on this. I guess it makes sense that it should be up to chokidar. I'll look into this. I'll go ahead and close my issue.
